import 'package:flutter/material.dart';

import '../core/models/media_item.dart';
import '../core/models/playlist.dart';

final DateTime _now = DateTime(2026, 6, 25, 10, 30);

List<LyricLine> _lyrics(List<String> lines) {
  return List<LyricLine>.generate(
    lines.length,
    (index) => LyricLine(
      time: Duration(seconds: 18 * index),
      text: lines[index],
    ),
  );
}

final List<MediaItem> seedAudioItems = <MediaItem>[
  MediaItem(
    id: 'song-blue-hour',
    kind: MediaKind.audio,
    title: 'Blue Hour Letters',
    artist: 'Mira Vale',
    album: 'City Windows',
    duration: const Duration(minutes: 4, seconds: 12),
    path: '/Music/City Windows/Blue Hour Letters.flac',
    folder: '/Music/City Windows',
    addedAt: _now.subtract(const Duration(hours: 8)),
    accentColor: const Color(0xFF3F7DFF),
    playCount: 18,
    isFavorite: true,
    fileSizeBytes: 34 * 1024 * 1024,
    fileSizeLabel: '34 MB',
    formatLabel: 'FLAC',
    lyrics: _lyrics(<String>[
      'Streetlights write in rain',
      'Your voice folds through the glass',
      'Blue hour keeps the city slow',
      'Every echo finds its frame',
      'I am listening from the window',
    ]),
  ),
  MediaItem(
    id: 'song-neon-archive',
    kind: MediaKind.audio,
    title: 'Neon Archive',
    artist: 'Paper Satellite',
    album: 'Tape Bloom',
    duration: const Duration(minutes: 3, seconds: 36),
    path: '/Music/Tape Bloom/Neon Archive.mp3',
    folder: '/Music/Tape Bloom',
    addedAt: _now.subtract(const Duration(days: 1, hours: 2)),
    accentColor: const Color(0xFFFF7A7A),
    playCount: 42,
    fileSizeBytes: 9 * 1024 * 1024,
    fileSizeLabel: '9 MB',
    formatLabel: 'MP3',
    lyrics: _lyrics(<String>[
      'Keep the hiss beneath the chorus',
      'Old machines remember light',
      'Every note returns in color',
      'Every frame is still alive',
    ]),
  ),
  MediaItem(
    id: 'song-sunlit-bassline',
    kind: MediaKind.audio,
    title: 'Sunlit Bassline',
    artist: 'The Velvet Loop',
    album: 'Afternoon Drive',
    duration: const Duration(minutes: 5, seconds: 4),
    path: '/Music/Afternoon Drive/Sunlit Bassline.m4a',
    folder: '/Music/Afternoon Drive',
    addedAt: _now.subtract(const Duration(days: 2, hours: 5)),
    accentColor: const Color(0xFFFFC857),
    playCount: 27,
    fileSizeBytes: 12 * 1024 * 1024,
    fileSizeLabel: '12 MB',
    formatLabel: 'M4A',
    lyrics: _lyrics(<String>[
      'Windows down in the middle lane',
      'A bright line running through the day',
      'Let the kick drum take the corner',
      'Let the chorus carry us away',
    ]),
  ),
  MediaItem(
    id: 'song-midnight-map',
    kind: MediaKind.audio,
    title: 'Midnight Map',
    artist: 'Nolan Reed',
    album: 'Quiet Engines',
    duration: const Duration(minutes: 2, seconds: 58),
    path: '/Music/Quiet Engines/Midnight Map.ogg',
    folder: '/Music/Quiet Engines',
    addedAt: _now.subtract(const Duration(days: 4)),
    accentColor: const Color(0xFF1FC7A6),
    playCount: 7,
    fileSizeBytes: 8 * 1024 * 1024,
    fileSizeLabel: '8 MB',
    formatLabel: 'OGG',
    lyrics: _lyrics(<String>[
      'The map is folded at the river',
      'The night is warmer than it seems',
      'Hold the line and keep it steady',
      'We can drive inside the dream',
    ]),
  ),
  MediaItem(
    id: 'song-quiet-rooms',
    kind: MediaKind.audio,
    title: 'Quiet Rooms',
    artist: 'Lena Shore',
    album: 'Small Signals',
    duration: const Duration(minutes: 3, seconds: 48),
    path: '/Music/Small Signals/Quiet Rooms.wav',
    folder: '/Music/Small Signals',
    addedAt: _now.subtract(const Duration(days: 6)),
    accentColor: const Color(0xFF9B7EDE),
    playCount: 12,
    fileSizeBytes: 39 * 1024 * 1024,
    fileSizeLabel: '39 MB',
    formatLabel: 'WAV',
    lyrics: _lyrics(<String>[
      'Quiet rooms can hold a storm',
      'Soft words gather at the door',
      'We keep the rhythm low and honest',
      'Nothing needs to ask for more',
    ]),
  ),
  MediaItem(
    id: 'song-paper-moon',
    kind: MediaKind.audio,
    title: 'Paper Moon Signal',
    artist: 'Paper Satellite',
    album: 'Tape Bloom',
    duration: const Duration(minutes: 4, seconds: 44),
    path: '/Music/Tape Bloom/Paper Moon Signal.mp3',
    folder: '/Music/Tape Bloom',
    addedAt: _now.subtract(const Duration(days: 9)),
    accentColor: const Color(0xFFFF9F4A),
    playCount: 31,
    fileSizeBytes: 11 * 1024 * 1024,
    fileSizeLabel: '11 MB',
    formatLabel: 'MP3',
    lyrics: _lyrics(<String>[
      'Paper moon over the antenna',
      'Static breaks into a song',
      'Call me back when the tape is turning',
      'I have been here all along',
    ]),
  ),
];

final List<MediaItem> seedVideoItems = <MediaItem>[
  MediaItem(
    id: 'video-lake-cut',
    kind: MediaKind.video,
    title: 'Lake Cut 04',
    artist: 'Camera Roll',
    album: 'Weekend Footage',
    duration: const Duration(minutes: 12, seconds: 45),
    path: '/Movies/Weekend/Lake Cut 04.mp4',
    folder: '/Movies/Weekend',
    addedAt: _now.subtract(const Duration(hours: 16)),
    accentColor: const Color(0xFF2F80ED),
    resolution: '4K',
    fileSizeBytes: 1229 * 1024 * 1024,
    fileSizeLabel: '1.2 GB',
    formatLabel: 'MP4',
  ),
  MediaItem(
    id: 'video-city-night',
    kind: MediaKind.video,
    title: 'City Night Walk',
    artist: 'Camera Roll',
    album: 'Street Notes',
    duration: const Duration(minutes: 28, seconds: 9),
    path: '/Movies/Street Notes/City Night Walk.mkv',
    folder: '/Movies/Street Notes',
    addedAt: _now.subtract(const Duration(days: 2)),
    accentColor: const Color(0xFF7C6FF6),
    resolution: '1080p',
    fileSizeBytes: 860 * 1024 * 1024,
    fileSizeLabel: '860 MB',
    formatLabel: 'MKV',
  ),
  MediaItem(
    id: 'video-course-one',
    kind: MediaKind.video,
    title: 'Flutter Player Prototype',
    artist: 'Courses',
    album: 'Local Lessons',
    duration: const Duration(minutes: 46, seconds: 18),
    path: '/Movies/Courses/Flutter Player Prototype.mov',
    folder: '/Movies/Courses',
    addedAt: _now.subtract(const Duration(days: 4)),
    accentColor: const Color(0xFF00A88F),
    resolution: '1440p',
    fileSizeBytes: 2458 * 1024 * 1024,
    fileSizeLabel: '2.4 GB',
    formatLabel: 'MOV',
  ),
  MediaItem(
    id: 'video-family-clip',
    kind: MediaKind.video,
    title: 'Family Clip Reel',
    artist: 'Camera Roll',
    album: 'Archive',
    duration: const Duration(minutes: 8, seconds: 22),
    path: '/Movies/Archive/Family Clip Reel.webm',
    folder: '/Movies/Archive',
    addedAt: _now.subtract(const Duration(days: 10)),
    accentColor: const Color(0xFFE85D75),
    resolution: '720p',
    fileSizeBytes: 240 * 1024 * 1024,
    fileSizeLabel: '240 MB',
    formatLabel: 'WEBM',
  ),
];

final List<Playlist> seedPlaylists = <Playlist>[
  Playlist(
    id: 'playlist-night-drive',
    name: '夜行车窗',
    description: '适合耳机和晚间驾驶的本地曲目',
    mediaIds: <String>[
      'song-blue-hour',
      'song-neon-archive',
      'song-midnight-map',
      'song-paper-moon',
    ],
    updatedAt: _now.subtract(const Duration(hours: 3)),
  ),
  Playlist(
    id: 'playlist-focus',
    name: '低亮度工作流',
    description: '不打扰的节奏、课程和片段',
    mediaIds: <String>[
      'song-quiet-rooms',
      'song-sunlit-bassline',
      'video-course-one',
    ],
    updatedAt: _now.subtract(const Duration(days: 1)),
  ),
];
